
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.2
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.2",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  username: 'username',
  password: 'password',
  roleId: 'roleId',
  branchId: 'branchId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RoleScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  isManager: 'isManager',
  parentRoleId: 'parentRoleId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RolePermissionScalarFieldEnum = {
  id: 'id',
  roleId: 'roleId',
  module: 'module',
  canView: 'canView',
  canCreate: 'canCreate',
  canEdit: 'canEdit',
  canDelete: 'canDelete',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BranchScalarFieldEnum = {
  id: 'id',
  name: 'name',
  location: 'location',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EmployeeScalarFieldEnum = {
  id: 'id',
  firstName: 'firstName',
  lastName: 'lastName',
  email: 'email',
  phone: 'phone',
  dateOfBirth: 'dateOfBirth',
  gender: 'gender',
  address: 'address',
  departmentId: 'departmentId',
  positionId: 'positionId',
  dateHired: 'dateHired',
  status: 'status',
  pictureUrl: 'pictureUrl',
  educationalDegree: 'educationalDegree',
  educationalInstitution: 'educationalInstitution',
  yearGraduated: 'yearGraduated',
  emergencyContactName: 'emergencyContactName',
  emergencyContactPhone: 'emergencyContactPhone',
  emergencyContactRelationship: 'emergencyContactRelationship',
  sssNumber: 'sssNumber',
  sssStatus: 'sssStatus',
  philHealthNumber: 'philHealthNumber',
  philHealthStatus: 'philHealthStatus',
  pagIbigNumber: 'pagIbigNumber',
  pagIbigStatus: 'pagIbigStatus',
  tinNumber: 'tinNumber',
  salaryType: 'salaryType',
  baseSalary: 'baseSalary',
  workFactor: 'workFactor',
  branchId: 'branchId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BenefitPlanScalarFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EmployeeBenefitScalarFieldEnum = {
  id: 'id',
  employeeId: 'employeeId',
  benefitPlanId: 'benefitPlanId',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DepartmentScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PositionScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  status: 'status',
  departmentId: 'departmentId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ShiftScalarFieldEnum = {
  id: 'id',
  name: 'name',
  startTime: 'startTime',
  endTime: 'endTime',
  workDays: 'workDays',
  isFlexi: 'isFlexi',
  flexiHours: 'flexiHours',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ScheduleScalarFieldEnum = {
  id: 'id',
  employeeId: 'employeeId',
  mondayId: 'mondayId',
  tuesdayId: 'tuesdayId',
  wednesdayId: 'wednesdayId',
  thursdayId: 'thursdayId',
  fridayId: 'fridayId',
  saturdayId: 'saturdayId',
  sundayId: 'sundayId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TimeRequestScalarFieldEnum = {
  id: 'id',
  employeeId: 'employeeId',
  type: 'type',
  date: 'date',
  startTime: 'startTime',
  endTime: 'endTime',
  reason: 'reason',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ActionLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  action: 'action',
  description: 'description',
  createdAt: 'createdAt'
};

exports.Prisma.LeaveRequestScalarFieldEnum = {
  id: 'id',
  employeeId: 'employeeId',
  type: 'type',
  startDate: 'startDate',
  endDate: 'endDate',
  reason: 'reason',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AttendanceScalarFieldEnum = {
  id: 'id',
  employeeId: 'employeeId',
  date: 'date',
  timeIn: 'timeIn',
  timeOut: 'timeOut',
  status: 'status',
  incidentReportUrl: 'incidentReportUrl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PayrollSettingScalarFieldEnum = {
  id: 'id',
  name: 'name',
  percentage: 'percentage',
  startTime: 'startTime',
  endTime: 'endTime',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PayrollPeriodScalarFieldEnum = {
  id: 'id',
  name: 'name',
  startDate: 'startDate',
  endDate: 'endDate',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PayrollRecordScalarFieldEnum = {
  id: 'id',
  payrollPeriodId: 'payrollPeriodId',
  employeeId: 'employeeId',
  salaryType: 'salaryType',
  baseRate: 'baseRate',
  totalHours: 'totalHours',
  ndHours: 'ndHours',
  otHours: 'otHours',
  lateHours: 'lateHours',
  undertimeHours: 'undertimeHours',
  absentDays: 'absentDays',
  leaveDays: 'leaveDays',
  basePay: 'basePay',
  absenceDeduction: 'absenceDeduction',
  undertimeDeduction: 'undertimeDeduction',
  lateDeduction: 'lateDeduction',
  leavePay: 'leavePay',
  adjustment: 'adjustment',
  totalBasicPay: 'totalBasicPay',
  sssDeduction: 'sssDeduction',
  phicDeduction: 'phicDeduction',
  hdmfDeduction: 'hdmfDeduction',
  hdmf2Deduction: 'hdmf2Deduction',
  subTotalGovtDues: 'subTotalGovtDues',
  isPositiveCrediting: 'isPositiveCrediting',
  ndPay: 'ndPay',
  otPay: 'otPay',
  holidayPay: 'holidayPay',
  grossTaxableIncome: 'grossTaxableIncome',
  taxDeduction: 'taxDeduction',
  hmoDeduction: 'hmoDeduction',
  sssLoan: 'sssLoan',
  hdmfLoan: 'hdmfLoan',
  companyLoan: 'companyLoan',
  otherDeduction: 'otherDeduction',
  subTotalDeductions: 'subTotalDeductions',
  diemAllowance: 'diemAllowance',
  allowance: 'allowance',
  subTotalAdditions: 'subTotalAdditions',
  grossPay: 'grossPay',
  netPay: 'netPay',
  regularOTRate: 'regularOTRate',
  nightDiffRate: 'nightDiffRate',
  ndStartTime: 'ndStartTime',
  ndEndTime: 'ndEndTime',
  holidayRegularRate: 'holidayRegularRate',
  holidaySpecialRate: 'holidaySpecialRate',
  workFactor: 'workFactor',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};


exports.Prisma.ModelName = {
  User: 'User',
  Role: 'Role',
  RolePermission: 'RolePermission',
  Branch: 'Branch',
  Employee: 'Employee',
  BenefitPlan: 'BenefitPlan',
  EmployeeBenefit: 'EmployeeBenefit',
  Department: 'Department',
  Position: 'Position',
  Shift: 'Shift',
  Schedule: 'Schedule',
  TimeRequest: 'TimeRequest',
  ActionLog: 'ActionLog',
  LeaveRequest: 'LeaveRequest',
  Attendance: 'Attendance',
  PayrollSetting: 'PayrollSetting',
  PayrollPeriod: 'PayrollPeriod',
  PayrollRecord: 'PayrollRecord'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
